spring:
  application:
    name: progetto_parking_system

  datasource:
    url: jdbc:mysql://localhost:3306/parking_system_db?createDatabaseIfNotExist=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: mysupersecretkey1234567890abcdef
  expiration: 86400000
server:
  port: 8080
